export enum Team {
  electronics = "electronics",
  devOps = "dev-ops",
  webTeam = "web-team",
  aiResearch = "ai-research",
  cloudComputing = "cloud-computing",
  cyberSecurity = "cyber-security",
  dataScience = "data-science",
  gameDevelopment = "game-development",
  iot = "iot",
  mobileDevelopment = "mobile-development",
  blockchain = "blockchain",
  networking = "networking",
  robotics = "robotics",
  softwareEngineering = "software-engineering",
  systemAdministration = "system-administration",
  uiUxDesign = "ui-ux-design",
  databaseManagement = "database-management",
  bioinformatics = "bioinformatics",
  embeddedSystems = "embedded-systems",
  quantumComputing = "quantum-computing",
}
